// This file is @generated by prost-build.
/// ---- Standard error payload (used with gRPC status; fatal errors may terminate the stream) ----
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Error {
    #[prost(enumeration = "ErrorCode", tag = "1")]
    pub code: i32,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    /// For logging/troubleshooting (stack, node ID, etc.)
    #[prost(string, tag = "3")]
    pub detail: ::prost::alloc::string::String,
}
/// ---- Structured task I/O description (for central routing and client negotiation) ----
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct IoTask {
    /// "embed","detect","ocr","asr","generate","tts",...
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// Allow multiple input types: "image/jpeg","audio/pcm;rate=16000","application/json"
    #[prost(string, repeated, tag = "2")]
    pub input_mimes: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Typical outputs: "application/json;schema=bbox_v1","audio/wav"
    #[prost(string, repeated, tag = "3")]
    pub output_mimes: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// e.g., max_hw=1024, max_batch=8, max_length=4096
    #[prost(map = "string, string", tag = "4")]
    pub limits: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    /// Empty means this task has no client-side tensor fast path.
    #[prost(string, tag = "5")]
    pub tensor_preprocess_id: ::prost::alloc::string::String,
    /// True means tensor requests for this task can be dynamically batched by the Hub.
    #[prost(bool, tag = "6")]
    pub tensor_batching_supported: bool,
}
/// ---- Capability declaration (retrieve at startup or on demand) ----
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Capability {
    /// "clip-embedder","ocr","llm","tts",...
    #[prost(string, tag = "1")]
    pub service_name: ::prost::alloc::string::String,
    /// Supported model IDs/versions
    #[prost(string, repeated, tag = "2")]
    pub model_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// "onnxrt-cuda","tensorrt","coreml","cpu"
    #[prost(string, tag = "3")]
    pub runtime: ::prost::alloc::string::String,
    /// Suggested max concurrency
    #[prost(uint32, tag = "4")]
    pub max_concurrency: u32,
    /// \["fp32","fp16","int8"\]
    #[prost(string, repeated, tag = "5")]
    pub precisions: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Resolution limits, ANE/NPU features, etc.
    #[prost(map = "string, string", tag = "6")]
    pub extra: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    /// Structured task capabilities (recommended)
    #[prost(message, repeated, tag = "7")]
    pub tasks: ::prost::alloc::vec::Vec<IoTask>,
    /// Version of current porotocal, should be semantic versioning. e.g., 1.0.0
    #[prost(string, tag = "8")]
    pub protocol_version: ::prost::alloc::string::String,
}
/// ---- Inference request (inbound message of bidi stream) ----
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InferRequest {
    /// Trace/correlation
    #[prost(string, tag = "1")]
    pub correlation_id: ::prost::alloc::string::String,
    /// "embed","classify","detect","ocr","asr","generate","tts",...
    #[prost(string, tag = "2")]
    pub task: ::prost::alloc::string::String,
    /// Raw payload (binary or UTF-8 text)
    #[prost(bytes = "vec", tag = "3")]
    pub payload: ::prost::alloc::vec::Vec<u8>,
    /// Task-specific parameters: model_id, conf_thres, stop, etc.
    #[prost(map = "string, string", tag = "4")]
    pub meta: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    /// --- Added: input content type and chunking control ---
    ///
    /// e.g. "image/jpeg","audio/pcm;rate=16000","application/json"
    #[prost(string, tag = "5")]
    pub payload_mime: ::prost::alloc::string::String,
    /// Chunk index (starting at 0)
    #[prost(uint64, tag = "6")]
    pub seq: u64,
    /// Optional: total number of chunks (omit if unknown)
    #[prost(uint64, tag = "7")]
    pub total: u64,
    /// Optional: byte offset of payload in the overall stream
    #[prost(uint64, tag = "8")]
    pub offset: u64,
}
/// ---- Inference response (outbound message of bidi stream) ----
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InferResponse {
    #[prost(string, tag = "1")]
    pub correlation_id: ::prost::alloc::string::String,
    /// Streaming partials or final result
    #[prost(bool, tag = "2")]
    pub is_final: bool,
    /// Result bytes; if JSON, specify via result_mime
    #[prost(bytes = "vec", tag = "3")]
    pub result: ::prost::alloc::vec::Vec<u8>,
    /// e.g., lat_ms, tokens, bboxes_count
    #[prost(map = "string, string", tag = "4")]
    pub meta: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    /// Populated only on failure (fatal errors may also terminate the stream)
    #[prost(message, optional, tag = "5")]
    pub error: ::core::option::Option<Error>,
    /// --- Added: output content type and chunking control ---
    ///
    /// Chunk index (starting at 0), used for incremental/audio/video chunks
    #[prost(uint64, tag = "6")]
    pub seq: u64,
    /// Optional: total number of chunks
    #[prost(uint64, tag = "7")]
    pub total: u64,
    /// Optional: byte offset of result in the overall output
    #[prost(uint64, tag = "8")]
    pub offset: u64,
    /// e.g. "application/json;schema=embedding_v1","audio/wav","image/png"
    #[prost(string, tag = "9")]
    pub result_mime: ::prost::alloc::string::String,
    /// Optional: explicit schema name (e.g., "bbox_v1","mask_rle_v1")
    #[prost(string, tag = "10")]
    pub result_schema: ::prost::alloc::string::String,
}
/// ---- Unified error codes (concise) ----
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ErrorCode {
    Unspecified = 0,
    InvalidArgument = 1,
    /// Downstream/hardware/resource unavailable
    Unavailable = 2,
    DeadlineExceeded = 3,
    Internal = 4,
}
impl ErrorCode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "ERROR_CODE_UNSPECIFIED",
            Self::InvalidArgument => "ERROR_CODE_INVALID_ARGUMENT",
            Self::Unavailable => "ERROR_CODE_UNAVAILABLE",
            Self::DeadlineExceeded => "ERROR_CODE_DEADLINE_EXCEEDED",
            Self::Internal => "ERROR_CODE_INTERNAL",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ERROR_CODE_UNSPECIFIED" => Some(Self::Unspecified),
            "ERROR_CODE_INVALID_ARGUMENT" => Some(Self::InvalidArgument),
            "ERROR_CODE_UNAVAILABLE" => Some(Self::Unavailable),
            "ERROR_CODE_DEADLINE_EXCEEDED" => Some(Self::DeadlineExceeded),
            "ERROR_CODE_INTERNAL" => Some(Self::Internal),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod inference_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// ---- Service contract ----
    #[derive(Debug, Clone)]
    pub struct InferenceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl InferenceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> InferenceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InferenceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            InferenceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Bidirectional stream: client sends chunks; server returns incremental/final results; ordered but non-blocking
        pub async fn infer(
            &mut self,
            request: impl tonic::IntoStreamingRequest<Message = super::InferRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::InferResponse>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/home_native.v1.Inference/Infer",
            );
            let mut req = request.into_streaming_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("home_native.v1.Inference", "Infer"));
            self.inner.streaming(req, path, codec).await
        }
        /// Capability declaration (backward compatibility: single capability; use StreamCapabilities for multiple)
        pub async fn get_capabilities(
            &mut self,
            request: impl tonic::IntoRequest<()>,
        ) -> std::result::Result<tonic::Response<super::Capability>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/home_native.v1.Inference/GetCapabilities",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("home_native.v1.Inference", "GetCapabilities"));
            self.inner.unary(req, path, codec).await
        }
        /// Recommended: server stream returns all capabilities (call at startup or after hot-reload)
        pub async fn stream_capabilities(
            &mut self,
            request: impl tonic::IntoRequest<()>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::Capability>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/home_native.v1.Inference/StreamCapabilities",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("home_native.v1.Inference", "StreamCapabilities"),
                );
            self.inner.server_streaming(req, path, codec).await
        }
        /// Health probe
        pub async fn health(
            &mut self,
            request: impl tonic::IntoRequest<()>,
        ) -> std::result::Result<tonic::Response<()>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/home_native.v1.Inference/Health",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("home_native.v1.Inference", "Health"));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod inference_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with InferenceServer.
    #[async_trait]
    pub trait Inference: std::marker::Send + std::marker::Sync + 'static {
        /// Server streaming response type for the Infer method.
        type InferStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::InferResponse, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        /// Bidirectional stream: client sends chunks; server returns incremental/final results; ordered but non-blocking
        async fn infer(
            &self,
            request: tonic::Request<tonic::Streaming<super::InferRequest>>,
        ) -> std::result::Result<tonic::Response<Self::InferStream>, tonic::Status>;
        /// Capability declaration (backward compatibility: single capability; use StreamCapabilities for multiple)
        async fn get_capabilities(
            &self,
            request: tonic::Request<()>,
        ) -> std::result::Result<tonic::Response<super::Capability>, tonic::Status>;
        /// Server streaming response type for the StreamCapabilities method.
        type StreamCapabilitiesStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::Capability, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        /// Recommended: server stream returns all capabilities (call at startup or after hot-reload)
        async fn stream_capabilities(
            &self,
            request: tonic::Request<()>,
        ) -> std::result::Result<
            tonic::Response<Self::StreamCapabilitiesStream>,
            tonic::Status,
        >;
        /// Health probe
        async fn health(
            &self,
            request: tonic::Request<()>,
        ) -> std::result::Result<tonic::Response<()>, tonic::Status>;
    }
    /// ---- Service contract ----
    #[derive(Debug)]
    pub struct InferenceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> InferenceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for InferenceServer<T>
    where
        T: Inference,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/home_native.v1.Inference/Infer" => {
                    #[allow(non_camel_case_types)]
                    struct InferSvc<T: Inference>(pub Arc<T>);
                    impl<
                        T: Inference,
                    > tonic::server::StreamingService<super::InferRequest>
                    for InferSvc<T> {
                        type Response = super::InferResponse;
                        type ResponseStream = T::InferStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<
                                tonic::Streaming<super::InferRequest>,
                            >,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Inference>::infer(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = InferSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/home_native.v1.Inference/GetCapabilities" => {
                    #[allow(non_camel_case_types)]
                    struct GetCapabilitiesSvc<T: Inference>(pub Arc<T>);
                    impl<T: Inference> tonic::server::UnaryService<()>
                    for GetCapabilitiesSvc<T> {
                        type Response = super::Capability;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(&mut self, request: tonic::Request<()>) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Inference>::get_capabilities(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetCapabilitiesSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/home_native.v1.Inference/StreamCapabilities" => {
                    #[allow(non_camel_case_types)]
                    struct StreamCapabilitiesSvc<T: Inference>(pub Arc<T>);
                    impl<T: Inference> tonic::server::ServerStreamingService<()>
                    for StreamCapabilitiesSvc<T> {
                        type Response = super::Capability;
                        type ResponseStream = T::StreamCapabilitiesStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(&mut self, request: tonic::Request<()>) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Inference>::stream_capabilities(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = StreamCapabilitiesSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/home_native.v1.Inference/Health" => {
                    #[allow(non_camel_case_types)]
                    struct HealthSvc<T: Inference>(pub Arc<T>);
                    impl<T: Inference> tonic::server::UnaryService<()> for HealthSvc<T> {
                        type Response = ();
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(&mut self, request: tonic::Request<()>) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Inference>::health(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = HealthSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for InferenceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "home_native.v1.Inference";
    impl<T> tonic::server::NamedService for InferenceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
