// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DownloadProgress {
    /// e.g. "bioclip-v2"
    #[prost(string, tag = "1")]
    pub model: ::prost::alloc::string::String,
    /// artifact currently transferring
    #[prost(string, tag = "2")]
    pub file: ::prost::alloc::string::String,
    #[prost(uint64, tag = "3")]
    pub bytes_done: u64,
    /// 0 when the remote did not report a length
    #[prost(uint64, tag = "4")]
    pub bytes_total: u64,
    #[prost(uint32, tag = "5")]
    pub files_done: u32,
    #[prost(uint32, tag = "6")]
    pub files_total: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ServiceState {
    /// "siglip","ppocr","insightface","bioclip"
    #[prost(string, tag = "1")]
    pub service: ::prost::alloc::string::String,
    /// per-service lifecycle
    #[prost(enumeration = "Phase", tag = "2")]
    pub phase: i32,
    /// set when phase == PHASE_FAILED
    #[prost(string, tag = "3")]
    pub error: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StatusSnapshot {
    #[prost(enumeration = "Phase", tag = "1")]
    pub phase: i32,
    /// hub build version
    #[prost(string, tag = "2")]
    pub version: ::prost::alloc::string::String,
    /// e.g. "darwin-arm64-metal"
    #[prost(string, tag = "3")]
    pub profile: ::prost::alloc::string::String,
    #[prost(int64, tag = "4")]
    pub started_at_unix_ms: i64,
    /// set while PHASE_DOWNLOADING
    #[prost(message, optional, tag = "5")]
    pub download: ::core::option::Option<DownloadProgress>,
    #[prost(message, repeated, tag = "6")]
    pub services: ::prost::alloc::vec::Vec<ServiceState>,
    /// last fatal error when PHASE_FAILED
    #[prost(string, tag = "7")]
    pub error: ::prost::alloc::string::String,
    /// monotonic; lets clients discard stale snapshots
    #[prost(uint64, tag = "8")]
    pub seq: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TailLogsRequest {
    /// ring-buffer lines replayed before live tail; 0 = live only
    #[prost(uint32, tag = "1")]
    pub backlog_lines: u32,
    /// "TRACE".."ERROR"; empty = "INFO"
    #[prost(string, tag = "2")]
    pub min_level: ::prost::alloc::string::String,
    /// true: keep streaming live entries; false: close after the backlog
    #[prost(bool, tag = "3")]
    pub follow: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LogEntry {
    #[prost(int64, tag = "1")]
    pub time_unix_ms: i64,
    /// "INFO","WARN","ERROR",...
    #[prost(string, tag = "2")]
    pub level: ::prost::alloc::string::String,
    /// tracing target, e.g. "lumen_hub::model_download"
    #[prost(string, tag = "3")]
    pub target: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub message: ::prost::alloc::string::String,
    /// structured tracing fields
    #[prost(map = "string, string", tag = "5")]
    pub fields: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
/// Hub/service lifecycle. The hub binds its port in PHASE_STARTING, so every
/// later phase (downloads included) is observable over this API.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Phase {
    Unspecified = 0,
    /// config parsed, control plane up
    Starting = 1,
    /// fetching model artifacts
    Downloading = 2,
    /// constructing models / moving weights to device
    Loading = 3,
    /// startup warmup inference
    Warmup = 4,
    /// data plane serving
    Ready = 5,
    /// terminal until restart; see StatusSnapshot.error
    Failed = 6,
    Stopping = 7,
}
impl Phase {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "PHASE_UNSPECIFIED",
            Self::Starting => "PHASE_STARTING",
            Self::Downloading => "PHASE_DOWNLOADING",
            Self::Loading => "PHASE_LOADING",
            Self::Warmup => "PHASE_WARMUP",
            Self::Ready => "PHASE_READY",
            Self::Failed => "PHASE_FAILED",
            Self::Stopping => "PHASE_STOPPING",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PHASE_UNSPECIFIED" => Some(Self::Unspecified),
            "PHASE_STARTING" => Some(Self::Starting),
            "PHASE_DOWNLOADING" => Some(Self::Downloading),
            "PHASE_LOADING" => Some(Self::Loading),
            "PHASE_WARMUP" => Some(Self::Warmup),
            "PHASE_READY" => Some(Self::Ready),
            "PHASE_FAILED" => Some(Self::Failed),
            "PHASE_STOPPING" => Some(Self::Stopping),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod control_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct ControlClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl ControlClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> ControlClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> ControlClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            ControlClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Snapshot of the current status; cheap, poll-safe.
        pub async fn get_status(
            &mut self,
            request: impl tonic::IntoRequest<()>,
        ) -> std::result::Result<tonic::Response<super::StatusSnapshot>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/lumen.control.v1.Control/GetStatus",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("lumen.control.v1.Control", "GetStatus"));
            self.inner.unary(req, path, codec).await
        }
        /// Pushes a fresh snapshot on every state change (download progress is
        /// throttled server-side, ~2/s). The first message is the current snapshot,
        /// so subscribers never start blind.
        pub async fn watch_status(
            &mut self,
            request: impl tonic::IntoRequest<()>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::StatusSnapshot>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/lumen.control.v1.Control/WatchStatus",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("lumen.control.v1.Control", "WatchStatus"));
            self.inner.server_streaming(req, path, codec).await
        }
        /// Structured log tail: optional ring-buffer backlog, then live entries.
        /// The on-disk log file remains the post-mortem source of truth.
        pub async fn tail_logs(
            &mut self,
            request: impl tonic::IntoRequest<super::TailLogsRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::LogEntry>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/lumen.control.v1.Control/TailLogs",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("lumen.control.v1.Control", "TailLogs"));
            self.inner.server_streaming(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod control_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with ControlServer.
    #[async_trait]
    pub trait Control: std::marker::Send + std::marker::Sync + 'static {
        /// Snapshot of the current status; cheap, poll-safe.
        async fn get_status(
            &self,
            request: tonic::Request<()>,
        ) -> std::result::Result<tonic::Response<super::StatusSnapshot>, tonic::Status>;
        /// Server streaming response type for the WatchStatus method.
        type WatchStatusStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::StatusSnapshot, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        /// Pushes a fresh snapshot on every state change (download progress is
        /// throttled server-side, ~2/s). The first message is the current snapshot,
        /// so subscribers never start blind.
        async fn watch_status(
            &self,
            request: tonic::Request<()>,
        ) -> std::result::Result<
            tonic::Response<Self::WatchStatusStream>,
            tonic::Status,
        >;
        /// Server streaming response type for the TailLogs method.
        type TailLogsStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::LogEntry, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        /// Structured log tail: optional ring-buffer backlog, then live entries.
        /// The on-disk log file remains the post-mortem source of truth.
        async fn tail_logs(
            &self,
            request: tonic::Request<super::TailLogsRequest>,
        ) -> std::result::Result<tonic::Response<Self::TailLogsStream>, tonic::Status>;
    }
    #[derive(Debug)]
    pub struct ControlServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> ControlServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for ControlServer<T>
    where
        T: Control,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/lumen.control.v1.Control/GetStatus" => {
                    #[allow(non_camel_case_types)]
                    struct GetStatusSvc<T: Control>(pub Arc<T>);
                    impl<T: Control> tonic::server::UnaryService<()>
                    for GetStatusSvc<T> {
                        type Response = super::StatusSnapshot;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(&mut self, request: tonic::Request<()>) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Control>::get_status(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetStatusSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/lumen.control.v1.Control/WatchStatus" => {
                    #[allow(non_camel_case_types)]
                    struct WatchStatusSvc<T: Control>(pub Arc<T>);
                    impl<T: Control> tonic::server::ServerStreamingService<()>
                    for WatchStatusSvc<T> {
                        type Response = super::StatusSnapshot;
                        type ResponseStream = T::WatchStatusStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(&mut self, request: tonic::Request<()>) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Control>::watch_status(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = WatchStatusSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/lumen.control.v1.Control/TailLogs" => {
                    #[allow(non_camel_case_types)]
                    struct TailLogsSvc<T: Control>(pub Arc<T>);
                    impl<
                        T: Control,
                    > tonic::server::ServerStreamingService<super::TailLogsRequest>
                    for TailLogsSvc<T> {
                        type Response = super::LogEntry;
                        type ResponseStream = T::TailLogsStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::TailLogsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Control>::tail_logs(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = TailLogsSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for ControlServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "lumen.control.v1.Control";
    impl<T> tonic::server::NamedService for ControlServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
