// This file is @generated by prost-build.
pub mod home_native {
    pub mod v1 {
        include!("home_native.v1.rs");
    }
}
pub mod lumen {
    pub mod control {
        pub mod v1 {
            include!("lumen.control.v1.rs");
        }
    }
}
