name = "lumen-shell"
product_name = "Lumen Hub"
identifier = "org.lumilio.lumen-hub"
version = "0.1.0-alpha.3"
out_dir = "../dist/shell"
binaries_dir = "../target/release"
before_packaging_command = "cargo build --release -p lumen-shell"
formats = ["wix"]
license_file = "../LICENSE"

[[binaries]]
path = "lumen-shell"
main = true
